In [2]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics.pairwise import cosine_similarity
import torch


In [4]:
## Generate some data
N=30

# data vectors
d1 = np.random.randn(N) + 1 #add an offset for Pearson vs cosine sim
d2 = d1 + np.random.randn(N)  # in the same direction as d1
d3 = -d1 + np.random.randn(N) # opposite dir of d1

## Coisne similariy: manual calculation

In [10]:
num = sum(d1*d2)
den = sum(d1*d1) * sum(d2**2)
cossim_manual = num/np.sqrt(den)

print(f'Manula calculation: cosine sim b/w d1 and d2 is {cossim_manual}')

Manula calculation: cosine sim b/w d1 and d2 is 0.8270573133860167


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])

a*b

array([ 4, 10, 18])

In [13]:
# check againts sklearn
# cossim_sklearn = cosine_similarity(d1,d2)

#ghe above wont work as we need to reshape the vectors
cossim_sklearn = cosine_similarity(d1.reshape(1,-1),d2.reshape(1,-1))
print(f'Sklearn cosine sim b/w d1 and d2: {cossim_sklearn}')

Sklearn cosine sim b/w d1 and d2: [[0.82705731]]


In [17]:
print(d1.reshape(1,-1).shape)  # vector as a 2d array
print(d1.shape)  # vector

# sklearn and torch needs first format (vectors represneted as 2d array)

(1, 30)
(30,)


# comparing with Pearson correlation coeff


In [18]:
#mean center
d1m = d1 - np.mean(d1)
d2m = d2 - np.mean(d2)

#manula calc
num = sum(d1m*d2m)
den = sum (d1m*d1m)*sum(d2m*d2m)
corr_manual = num/np.sqrt(den)

#numpy
corr_np = np.corrcoef(d1,d2)[0,1]

#cosine sim using mean centered data
cossimM_sklearn = cosine_similarity(d1m.reshape(1,-1), d2m.reshape(1,-1))


#print all results
print(f'Manual calculation: Pearson corr b/w d1 and d2 is {corr_manual}')
print(f'Numpy corrcoef(): Pearson corr b/w d1 and d2 is {corr_np}')
print(f'sklearn:  cosine sim  b/w d1m and d2m is {cossimM_sklearn}')
print(f'sklearn:  cosine sim  b/w d1 and d2 is {cossim_sklearn}')

# Pearson correlation coeff is same as cosine similarity if data is mean centered (mean=0)

Manual calculation: Pearson corr b/w d1 and d2 is 0.7242485106559656
Numpy corrcoef(): Pearson corr b/w d1 and d2 is 0.7242485106559656
sklearn:  cosine sim  b/w d1m and d2m is [[0.72424851]]
sklearn:  cosine sim  b/w d1 and d2 is [[0.82705731]]


## cosine similairy in pytorch

In [19]:
torch.cosine_similarity(d1,d2)

TypeError: cosine_similarity(): argument 'x1' (position 1) must be Tensor, not numpy.ndarray

In [20]:
type(torch.tensor(d1))

torch.Tensor

In [21]:
# the args should be tensor, not array
torch.cosine_similarity(torch.tensor(d1), torch.tensor(d2))

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [22]:
torch.cosine_similarity(torch.tensor(d1).view(1,-1), torch.tensor(d2).view(1,-1))

tensor([0.8271], dtype=torch.float64)

In [40]:
a=np.array([1,23,4])
print(a.shape)
print(a)

(3,)
[ 1 23  4]


In [41]:
print(a.reshape(1,-1))
print(a.reshape(1,-1).shape)

[[ 1 23  4]]
(1, 3)


In [42]:
print(a.reshape(-1,1))#.shape
print(a.reshape(-1,1).shape)

[[ 1]
 [23]
 [ 4]]
(3, 1)
