In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# create the 2 tensor objects
vocab_size = 5000
embed_dim = int(vocab_size**(1/2))
print(f'{vocab_size:,} tokens in vocab and {embed_dim} embedding dimensions')

5,000 tokens in vocab and 70 embedding dimensions


In [3]:
E = nn.Embedding(vocab_size, embed_dim) #input [in X out]
L = nn.Linear(embed_dim, vocab_size)  #input [out X in]

print(E)
print(L)
print(f'\nEmbedding matrix size: {E.weight.shape}')
print(f'Linear matreix size: {L.weight.shape}')

Embedding(5000, 70)
Linear(in_features=70, out_features=5000, bias=True)

Embedding matrix size: torch.Size([5000, 70])
Linear matreix size: torch.Size([5000, 70])


\explopre their attributes

In [4]:
len(dir(E)), len(dir(L))

(129, 123)

In [5]:
dir(E)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_fill_padding_idx_with_zero',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules

In [8]:
# unique attritbues of each type
attrE = dir(E)
attrL = dir(L)

print('Attrributes only in Embedding')
for e in attrE:
    if e not in attrL:
        print(' ' +e)


print('\n\nAttrributes only in Linear')
for l in attrL:
    if l not in attrE:
        print(' ' +l)

Attrributes only in Embedding
 _fill_padding_idx_with_zero
 embedding_dim
 from_pretrained
 max_norm
 norm_type
 num_embeddings
 padding_idx
 scale_grad_by_freq
 sparse


Attrributes only in Linear
 bias
 in_features
 out_features


indexing their vectors


In [9]:
print(E.weight)
print(' ')
print(L.weight)

Parameter containing:
tensor([[ 0.3875, -0.2554, -0.0241,  ..., -0.2724, -1.0058,  0.4520],
        [-1.4386,  1.2612, -0.5140,  ...,  0.3780, -0.2661,  1.3075],
        [-0.1758,  1.8739,  1.3123,  ...,  0.2986,  0.3940,  0.6581],
        ...,
        [ 0.0237,  1.0179, -1.2630,  ...,  0.5935,  0.5056, -0.4228],
        [-0.1758,  0.1083, -0.5631,  ...,  0.3422,  1.2250,  1.2936],
        [-0.4512, -0.7831,  0.9035,  ...,  0.0901,  1.2556, -0.3130]],
       requires_grad=True)
 
Parameter containing:
tensor([[-0.0502, -0.0671,  0.0977,  ..., -0.0917,  0.0670, -0.0776],
        [ 0.1112, -0.0927,  0.0520,  ...,  0.0824, -0.1127, -0.1019],
        [ 0.0199, -0.0337,  0.0737,  ..., -0.0910,  0.0409,  0.0645],
        ...,
        [-0.0014, -0.0551,  0.1041,  ...,  0.0976,  0.0914,  0.1014],
        [ 0.0077, -0.0776, -0.0100,  ..., -0.0181, -0.0176, -0.0862],
        [-0.1156, -0.0038,  0.0038,  ..., -0.0970, -0.0852,  0.1179]],
       requires_grad=True)


In [11]:
tokenidx = torch.tensor([1])
E(tokenidx) # emulaters one hot encoding

tensor([[-1.4386,  1.2612, -0.5140,  0.9556, -0.2304,  0.5485, -0.0558,  0.5411,
         -0.6446,  1.0935,  0.0613,  0.0670, -1.5341, -1.2291, -0.0214, -0.1050,
         -0.6782, -0.2176, -0.5108, -0.6156, -0.0923, -0.0560,  0.7473, -0.5905,
          0.6720, -0.2263,  0.0920, -1.7169,  0.1925, -0.9999, -1.2995, -0.4284,
          0.2939, -1.6564,  1.3641,  1.3400,  0.5402,  0.5719,  0.2240, -1.1140,
          0.6492,  2.3213,  0.0476, -0.2344, -1.0540,  1.3522,  1.0682, -0.5033,
         -0.3513, -0.0350, -1.5617, -0.2588, -0.5635,  0.1417, -0.1068,  1.2529,
         -1.2172, -1.6056,  0.6365,  0.4061,  0.5729, -2.0690, -1.5862, -0.3745,
         -1.1023,  0.8391,  0.3190,  0.3780, -0.2661,  1.3075]],
       grad_fn=<EmbeddingBackward0>)

In [12]:
L(tokenidx)
#this wont work

RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

In [13]:
#  use this
L.weight[tokenidx,:]

tensor([[ 0.1112, -0.0927,  0.0520,  0.1153, -0.0635,  0.0643, -0.0502, -0.1075,
          0.0204, -0.0824, -0.0919,  0.0604,  0.0892, -0.0041, -0.0757, -0.0743,
          0.0442,  0.1074,  0.1150, -0.0764, -0.0490,  0.0204, -0.1076,  0.0363,
         -0.0140,  0.0540, -0.0854,  0.0154, -0.0139,  0.0440,  0.0952,  0.0080,
          0.0452,  0.0612, -0.0989, -0.0886,  0.1187, -0.0585, -0.1144, -0.0870,
          0.0712,  0.0134, -0.0959, -0.0432,  0.1128,  0.0076,  0.0513,  0.0970,
         -0.0009,  0.0130, -0.0607, -0.0584,  0.0051,  0.0772,  0.0824, -0.0608,
         -0.1052,  0.0653,  0.0388,  0.1161, -0.0729, -0.0343,  0.0830,  0.0981,
         -0.0156,  0.0267,  0.0120,  0.0824, -0.1127, -0.1019]],
       grad_fn=<IndexBackward0>)

In [15]:
torch.zeros(vocab_size,1).shape

torch.Size([5000, 1])