In [1]:
# this notebook exlains training of a single weight
# this weight starts off at 0 and tries to fit the value of pi
# we use mean square error fun

In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
#init the weight value
w = torch.tensor([0.],requires_grad=True)
# require_grad initiates a computational graph to associate wth this variable 
# and that graph necessary to optmise

target = torch.tensor([torch.pi])

#learning rate
lr = 0.01

# create the optimizers
optimizer = torch.optim.SGD([w],lr=lr)

#no of training iterations
numIters = 150

#init results matrices
all_losses = np.zeros(numIters)
all_weights = np.zeros(numIters+1)
all_weights[0] = w.item() #initial value


# trainng loop
for i in range(numIters):
    #train the wieght
    optimizer.zero_grad()
    loss = (w-target)**2
    loss.backward()
    optimizer.step()

    #store loss and update the weight value
    all_losses[i]= loss.item()
    all_weights[i+1] = w.item()

    

In [7]:
w

tensor([2.9899], requires_grad=True)

# the opmtimizer competition

In [9]:
# here we have 3 diff variables which are trainined on diff optimizer funcs


In [20]:
wSGD = torch.tensor([2.], requires_grad=True)
wAdam = torch.tensor([2.], requires_grad=True)
wAdamW = torch.tensor([2.], requires_grad=True)

target = torch.tensor([5.])

#lr
learningrateSGD = .05
learningrateAdm = .05

#create optimizers
optimizerSGD = torch.optim.SGD([wSGD],lr=learningrateSGD)
optimizerAdam = torch.optim.Adam([wAdam],lr=learningrateAdm)
optimizerAdamW = torch.optim.AdamW([wAdamW],lr=learningrateAdm)

numIters = 50


all_losses = np.zeros((3,numIters))
all_weights = np.zeros((3,numIters+1))
all_weights[:,0] = wSGD.item() #initial value


for i in range(numIters):
    #train the SGD wieght
    optimizerSGD.zero_grad()
    lossSGD = (wSGD-target)**2
    lossSGD.backward()
    optimizerSGD.step()

    #train with adam
    optimizerAdam.zero_grad()
    lossAdam = (wAdam-target)**2
    lossAdam.backward()
    optimizerAdam.step()

    
    #train with adamW
    optimizerAdamW.zero_grad()
    lossAdamW = (wAdamW-target)**2
    lossAdamW.backward()
    optimizerAdamW.step()

    #store the losses and updated weight value
    all_losses[0,i]= lossSGD.item()
    all_losses[1,i]= lossAdam.item()
    all_losses[2,i]= lossAdamW.item()
    
    all_weights[0,i+1] = wSGD.item()
    all_weights[1,i+1] = wAdam.item()
    all_weights[2,i+1] = wAdamW.item()
    

In [12]:
lossSGD = (wSGD-target)**2

In [19]:
lossSGD


tensor([9.], grad_fn=<PowBackward0>)

![optm](Optmizers.png)

In [23]:
# here SGD does really well compared to adam, adamW

In [24]:
wSGD

tensor([4.9845], requires_grad=True)

In [25]:
wAdam

tensor([4.1481], requires_grad=True)

In [26]:
wAdamW

tensor([4.0849], requires_grad=True)

In [27]:
# so simple models would be better with simple ompitmizers like SGD
# adam works with complex usecases like image recog, LLM etc. 