In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Using dropout (using Dropout Class)

In [5]:
prob = .2

dropout = nn.Dropout(p=prob)
x = torch.ones(100)
print('initial data vector:\n ',x,'\n')


y=dropout(x)
print('"Raw" post dropout vector:\n ',y,'\n')
# the non zero activations will be scaled up (that is why we get 1.25)


#normalized
print('normed post dropout vector:\n ',y*(1-prob),'\n')

#how many were dropped
print(f'{100*torch.sum(y==0)/len(x)}% dropped (expected {prob*100:.1f}%)')

# dropout is probablistic, so each time you run this cell different sets of units are dropped

initial data vector:
  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) 

"Raw" post dropout vector:
  tensor([0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500,
        1.2500, 0.0000, 0.0000, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000, 1.2500,
        1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 0.0000, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1

In [6]:
x.sum(),y.sum(), (y*(1-prob)).sum()
# as Pytorch internally scaled up non-dropout units, we get sum closer, or else it would be diff (81)

(tensor(100.), tensor(101.2500), tensor(81.))

How to switch off dropout

In [7]:
#dropout turned off when evaluating model
dropout.eval() #in actual code this will be model.eval()
y = dropout(x)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


DROPOUT USING FUNCTION

In [8]:
F.dropout(x,p=prob)

tensor([1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 0.0000,
        1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 0.0000, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 0.0000, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000, 1.2500,
        0.0000])

In [12]:
# why 3 methods???
# bcoz of ease of toggling dropout

#dropout used only for training, you want to turn off dropout during evaluation, prediction, production etc


Toggling dropout

In [11]:
#dropout turned off when evaluating model
dropout.eval() #in actual code this will be model.eval() [This actually turns off gradient calculation, reg techniques like dropout etc]
y = dropout(x)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [14]:
# F.dropout() is not deactivated in eval mode
dropout.eval()
y = F.dropout(x,p=.2)
print(y)

tensor([1.2500, 0.0000, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 0.0000, 0.0000, 0.0000, 1.2500, 0.0000, 1.2500, 1.2500,
        0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 0.0000, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 0.0000, 0.0000, 0.0000,
        0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500])


In [16]:
# but can you manually swithc it off???

y = F.dropout(x,training=False)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [18]:
# model needs to be reset after toggling into eval mode
dropout.train()
y = dropout(x)
print('train() mode on:\n',y,'\n') #with dropout

dropout.eval()
y = dropout(x)
print('eval() mode on:\n',y,'\n')


# dropout.train()
y = dropout(x)
print('eval() remains on:\n',y,'\n') #still w/o dropout

train() mode on:
 tensor([1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500,
        0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        0.0000, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500,
        0.0000]) 

eval() mode on:
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [19]:
# explicitly switch it back to train
dropout.train()
y = dropout(x)
print('eval() remains on:\n',y,'\n')

eval() remains on:
 tensor([1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500,
        0.0000, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 0.0000, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 0.0000, 1.2500,
        0.0000, 0.0000, 1.2500, 1.2500, 1.2500, 0.0000, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 0.0000, 0.0000, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500, 1.2500,
        1.2500]) 

